export const CREATE_BLOG = "CREATE_BLOG"
export const UPDATE_BLOG = "UPDATE_BLOG"
export const DELETE_BLOG = "DELETE_BLOG"
export const SINGLE_BLOG = "SINGLE_BLOG"
export const GET_BLOGS = "GET_BLOGS"

// export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST"
// export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS"
// export const CREATE_BLOG_FAILURE = "CREATE_BLOG_FAILURE"

// export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST"
// export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS"
// export const UPDATE_BLOG_FAILURE = "UPDATE_BLOG_FAILURE"

// export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST"
// export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS"
// export const DELETE_BLOG_FAILURE = "DELETE_BLOG_FAILURE"

// export const FETCH_ALL_BLOGS = "FETCH_ALL_BLOGS"
// export const FETCHED_ALL_BLOGS = "FETCHED_ALL_BLOGS"

// export const FETCH_SINGLE_BLOG_REQUEST = "FETCH_SINGLE_BLOG_REQUEST"
// export const FETCH_SINGLE_BLOG_SUCCESS = "FETCH_SINGLE_BLOG_SUCCESS"
// export const FETCH_SINGLE_BLOG_FAILURE = "FETCH_SINGLE_BLOG_FAILURE"


export const FETCH_BLOG = "FETCH_BLOG"
export const FETCHED_BLOG = "FETCHED_BLOG" 
